package com.zykj.samplechat.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table GROUPS.
 */
public class Groups {

    /** Not-null value. */
    private String groupsId;
    private String name;
    private String portraitUri;
    private String displayName;
    private String role;
    private String bulletin;
    private String timestamp;
    private String nameSpelling;

    public Groups() {
    }

    public Groups(String groupsId) {
        this.groupsId = groupsId;
    }

    public Groups(String groupsId, String name, String portraitUri, String displayName, String role, String bulletin, String timestamp) {
        this.groupsId = groupsId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.role = role;
        this.bulletin = bulletin;
        this.timestamp = timestamp;
    }

    public Groups(String timestamp, String role, String displayName, String portraitUri, String name, String groupsId) {
        this.timestamp = timestamp;
        this.role = role;
        this.displayName = displayName;
        this.portraitUri = portraitUri;
        this.name = name;
        this.groupsId = groupsId;
    }

    public Groups(String groupsId, String name, String portraitUri, String role) {
        this.groupsId = groupsId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.role = role;
    }

    public Groups(String groupsId, String name, String portraitUri) {
        this.groupsId = groupsId;
        this.name = name;
        this.portraitUri = portraitUri;
    }

    public Groups(String groupsId, String name, String portraitUri, String displayName, String role, String bulletin, String timestamp, String nameSpelling) {
        this.groupsId = groupsId;
        this.name = name;
        this.portraitUri = portraitUri;
        this.displayName = displayName;
        this.role = role;
        this.bulletin = bulletin;
        this.timestamp = timestamp;
        this.nameSpelling = nameSpelling;
    }
    /** Not-null value. */
    public String getGroupsId() {
        return groupsId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGroupsId(String groupsId) {
        this.groupsId = groupsId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getBulletin() {
        return bulletin;
    }

    public void setBulletin(String bulletin) {
        this.bulletin = bulletin;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getNameSpelling() {
        return nameSpelling;
    }

    public void setNameSpelling(String nameSpelling) {
        this.nameSpelling = nameSpelling;
    }

}
